env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      env: JOB=Xcode7.3
    - os: osx
      language: objective-c
      osx_image: xcode8
      env: JOB=Xcode8

install:
  - carthage bootstrap --use-submodules --no-build
  - pod repo update --silent

script:
  - if [[ "$JOB" == "Xcode7.3" ]]; then pod lib lint; fi
  - set -o pipefail
  - xcodebuild test -workspace APIKit.xcworkspace -scheme APIKit | xcpretty -c
  - xcodebuild test -workspace APIKit.xcworkspace -scheme APIKit -sdk iphonesimulator -destination "name=iPhone 6s" | xcpretty -c
  - xcodebuild test -workspace APIKit.xcworkspace -scheme APIKit -sdk appletvsimulator -destination "name=Apple TV 1080p" | xcpretty -c
  - carthage build --no-skip-current

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
